### ISSUE TITLE
Error adding XC server

### ISSUE THREAD

**Issue by ghost** [andrefmsilva/iplaytvaio-bugs#80]
**Describe the bug**
When I try to add the server shown in attached picture I receive an error. Same server works in tvOS release without any problems.

Traffic analysis hints that the server closes a socket causing first request for get_live_streams to fail, but I also see that data is actually sent from the server. I also see that keep alive works on the server.

**To Reproduce**
1. Go to settings
2. Click on stream sources
3. Click on add Xtream server
4. Fill in the details as in picture. Password is also catchuptv5. 
5. Click on Save

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
iPad OS 15.5 beta

**iPlayTV AIO version**: Version of iPlayTV this bug occurred on (can be found in Settings tab)
v1.0 20220319.0

**iOS device**: For example iPhone XS, iPad mini, etc.
iPad air 3

**Jailbroken**: Whether or not your device is jailbroken
No

**Reproducible:** Can you reproduce it every time? Or is it random?
Yes

**Expected behavior**

I expected the server to be added without problem, because it works in tvOS version

**Screenshots**
If possible, add screenshots to help show the problem.

![959F9FCC-1880-4F9F-A418-B66701253CC2](https://user-images.githubusercontent.com/103790736/163652169-209e6020-0b21-4c1b-9a3f-27147afe3ccb.png)
![914AF5B4-8C02-4862-94F6-EED9B7CA6F3D](https://user-images.githubusercontent.com/103790736/163652177-f3402387-9ceb-4d19-9ac5-f95e856339d4.png)
![7F963CEF-3A5B-4E5C-A425-47218BE75163](https://user-images.githubusercontent.com/103790736/163652179-56fc355b-d739-41a4-a710-da8e732ac84f.png)
![2E9A6497-5874-4BA1-8248-FBFD09F7F4EA](https://user-images.githubusercontent.com/103790736/163652180-af58565a-f4b7-435e-8c80-36151526c8c4.png)
![5424B3BB-86C5-4DD7-9225-92791622C4AF](https://user-images.githubusercontent.com/103790736/163652182-a9031a3f-cd1a-4e8f-9427-534bfc84a36c.png)

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by ghost** [comment]
Problem is also found on iPhone XS Max, iOS 15.4.1

**Comment by andrefmsilva** [comment]
Fixed but not released yet. it was a parsing problem in the category api

**Comment by ghost** [comment]
Problem is still present in May 26 beta.

26. maj 2022 12.14 af ***@***.***:
